reset_integral:
  target:
    entity:
      integration: dimmer_thermostat
      domain: climate
  fields:
    preload:
      required: false
      example: 20
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"
          mode: box
